from lichees_client.endpoints.account import Account
from lichees_client.endpoints.broadcast import Broadcast
from lichees_client.endpoints.challenges import Challenges
from lichees_client.endpoints.chess_bot import ChessBot
from lichees_client.endpoints.games import Games
from lichees_client.endpoints.messaging import Messaging
from lichees_client.endpoints.relations import Relations
from lichees_client.endpoints.simulations import Simulations
from lichees_client.endpoints.studies import Studies
from lichees_client.endpoints.teams import Teams
from lichees_client.endpoints.tournaments import Tournaments
from lichees_client.endpoints.users import Users
